### PR TITLE
added example for using SplitOutputStream

### PR DESCRIPTION
**Pull request by yarix**

### CODE REVIEW

**Comment by srikanth-lingala** [comment]
Before I merge this, I have to add some tests to make sure that this works as expected. Using `SplitOutputStream` with `ZipOutputStream` should work. Zip4j does splitting this way, but I think there are no integration tests yet using this combination of `SplitOutputStream` and `ZipOutputStream`. I will check that, add if necessary, and merge this PR.

PS: If you want to use `SplitOutputStream`, you have to use a `File`, as it is one of the parameters in the constructor. If you have access to a `File` object, why don't you use `ZipFile` api directly? Is there any particular reason for using `ZipOutputStream` even when you have access to a `File`? Don't get me wrong, I am just curious to know the use case behind it.

**Comment by yarix** [comment]
the use case i have is that:
I'm streaming data from large DB table to CSV. I've started with simple streaming solution like in the readme example. but then it turned out that the files gets too large for downloading & uploading. using the `SplitOutputStream` i was able to get result with very minor change to the code (adding another if-else in `initializeZipOutputStream` method, to handle a 'shouldSplit' flag.

i hope, i explained my self properly. 

at first, by looking in the exiting example, it seemed like i first need to extract the data differently (to files) and then use zip split operation. this of course will take much more disk space and time.

BTW - i was able to stream several GB of data directly into split files and i was also able to unzip the files properly (see #180 )

**Comment by srikanth-lingala** [comment]
`SplitOutputStream` was meant to be used for internal purposes only. If I add it to the documentation now, it means that this is officially supported. That means that I have to keep backward compatibility in mind whenever I make any changes to `SplitOutputStream`. To be honest, I have mixed feelings with that. There is no reason why `SplitOutputStream` should not work. It will work, zip4j uses it internally, but it is just that if I make it official, as I said, I will loose the flexibility to maintain it.

Maybe you can use this api without making it official in the documentation. WDYT?

**Comment by srikanth-lingala** [comment]
As mentioned in the comment above, I would not want to make this class for official use. You can definitely use this class, but this class was and is meant for internal purposes. I will close this PR.

**Comment by yarix** [comment]
i understand your support concern. the `SplitOutputStream` is working great, it solved my need.
i find this capability as big advantage in zip4j. 

i do believe that zip4j need to add the split zip feature also to streams (i mean officially :) ). 
maybe move the split size to the zip-parameters and use it internally when either files or streams are added to the zipFile? this way the `SplitOutputStream` can stay internal class.

The existing feature list doesn't mention that the following are mutual exclusive.
 * Support for streams (ZipInputStream and ZipOutputStream)
 * Create or extract files from Split Zip files (Ex: z01, z02,...zip)

**Comment by srikanth-lingala** [comment]
I appreciate your feedback, but it will not be possible to support split files when using ZipOutputStream. For split zip, you need to work with files. When you use files, you can either use `ZipFile` api (which will be the case in almost all of the cases), or in exceptional cases like yours, you can use `SplitOutputStream`. But to support split zip with ZipOutputStream will not be possible, because ZipOutputStream takes in any OutputStream as a parameter, and there will be no way to inform that OutputStream that a part of the split file has ended and another has to start. When creating split zip, zip4j needs more control over when to end a part and when to start a new one, and also be able to rename the existing part. This will be almost impossible to do with generic OutputStreams. Of course nothing is impossible, but the complexity it brings does not add much value, especially when you can either use `ZipFile` api or `SplitOutputStream`.

**Pull request closed without merging**
