### PR TITLE
Use SecureRandom instead of Random to implement a cryptographically s…

### PR DESCRIPTION
**Pull request by PlayerA**
…trong random number

Use SecureRandom instead of Random to implement a cryptographically strong random number

### CODE REVIEW

**Comment by PlayerA** [comment]
This is related about the issue
https://github.com/srikanth-lingala/zip4j/issues/443

**Comment by srikanth-lingala** [comment]
Thanks for the pull request

**Comment by srikanth-lingala** [comment]
PR included in v2.11.2 released today

**Comment by PlayerA** [comment]
Thanks for the update

**Pull request merged**
