### PR TITLE
added file not found exception type

### PR DESCRIPTION
**Pull request by yausername**

### CODE REVIEW

**Comment by yausername** [comment]
@srikanth-lingala excuse my impatience. Can you have a look at this?

**Comment by srikanth-lingala** [comment]
I will merge it, but can you please update the javadoc for the method `extractFile` as well, and add a note in the last sentence in the existing javadoc and extend it with this exception type? Thanks.

**Comment by yausername** [comment]
I have updated the javadoc. Let me know if any changes are needed.

**Comment by srikanth-lingala** [comment]
Looks good. Will merge it.

**Pull request merged**
