### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by Marcono1234**
Notable changes:
- Consistently capitalize `Java`, `Zip4j`, `GitHub`, `API`
- Consistently lowercase `zip`
- Fix spelling mistakes
- Don't format "Features" section as code block
- Change time span references (e.g. "10 years back") to absolute years (e.g. "back in 2009") to prevent them becoming incorrect in the next year

Additionally in my opinion it would be good to change all links to inline links (`[link text](https://example.com)`) instead of using link references (except maybe link 7 which is used twice) because it is rather inconvenient when editing the README to have to look at the end of the file to find out where a link leads to.

Maybe for "CP437" it might also make sense to add a link to the [Wikipedia article](https://en.wikipedia.org/wiki/Code_page_437)?

### CODE REVIEW

**Comment by srikanth-lingala** [comment]
Thanks again for improving the documentation. 

Regarding your point about having links inline within documentation (and not as numbered links at the bottom), it is probably a matter of taste, but to me having numbered links makes the text more readable when editing. I understand your point that you have to scroll to the top and the bottom to see where it is pointing to, but links are mostly changed quite rarely, but editing the documentation is done a bit more often, and IMO, makes the text a bit more readable when editing.

**Comment by Marcono1234** [comment]
No problem.

When you merged `master` into this branch, it added the code block formatting to the "Features" section again. Is that intended or should I revert it?

**Comment by srikanth-lingala** [comment]
@Marcono1234 

> When you merged master into this branch, it added the code block formatting to the "Features" section again. Is that intended or should I revert it?

No, that was not intended. I will revert it.

I resolved conflicts and will merge this PR now, and will revert the Features formatting again.

**Comment by srikanth-lingala** [comment]
I just checked the README on master and the features block has ``` and not `~~~`.

**Comment by Marcono1234** [comment]
Thanks for merging it. Though my point was that (regardless of whether <code>\`\`\`</code> or `~~~` is used for that section) the "Features" section should in my opinion not be a code block. I don't see any advantages in that, it is rather confusing and decreases readiblity.

**Comment by srikanth-lingala** [comment]
Yes, I remember our discussion now. I guess the reason why I had it in the first place was to highlight the block, and that was a noob way of doing it. I just edited it and I agree that it looks better without the code formatting. I will remove it.

**Pull request merged**
